### ISSUE TITLE
The app crashes on initial setup when Steam is not installed in the default location

### ISSUE THREAD

**Issue by jarrettgilliam** [jarrettgilliam/AutoGame#6]
No logs are written out until the `%LOCALAPPDATA%\AutoGame` folder is created. This also keeps the app from crashing.

Log.txt:
```
1/6/2022 9:15:11 PM Error: handling application loaded: System.IO.FileNotFoundException: The software path is invalid
File name: 'C:\Program Files (x86)\Steam\Steam.exe'
   at AutoGame.Infrastructure.Services.AutoGameService.ValidateConfig(Config config)
   at AutoGame.Infrastructure.Services.AutoGameService.ApplyConfiguration(Config config)
   at AutoGame.ViewModels.MainWindowViewModel.OnLoaded() in C:\Users\jarrett\Code\C#\AutoGame\src\AutoGame\ViewModels\MainWindowViewModel.cs:line 116
```

**Comment by jarrettgilliam** [comment]
Resolved with release v1.0.4.
